---
year: 2022
month: 1
employees:
  - 
    first_name: A
    gender: M
    last_name: A
    leaves: 
      - 
        end_date: 2022-01-20
        start_date: 2022-01-01
      - 
        end_date: 2022-06-15
        start_date: 2022-06-01
    mandatory_shifts: 
      - 2022-01-22
      - 2022-01-26
    free_days: 2
  - 
    first_name: B
    gender: M
    last_name: B
  - 
    first_name: C
    gender: M
    last_name: C
  - 
    first_name: D
    gender: M
    last_name: D
  - 
    first_name: E
    gender: M
    last_name: E
  - 
    first_name: F
    gender: F
    last_name: F
